### ISSUE TITLE
Filerun user-files mapping

### ISSUE THREAD

**Issue by PTRFRLL** [JamesTeague/unraid-templates#1]
At present, the Filerun template maps files to container path: `/filerun/user-files`. I believe the correct mapping should just be `/user-files`. All the files I've uploaded so far are not mapped to Unraid, they are within the container itself.

**Comment by CorneliousJD** [comment]
The /var/www/html volume mapping is also missing as well, it is required for saving the actual config itself. 

https://docs.filerun.com/docker
